<?php
/**
 * Copyright (c) 2017.
 * @author Nikola Tesic (nikolatesic@gmail.com)
 */

/**
 * Created by PhpStorm.
 * User: Nikola
 * Date: 7/4/2017
 * Time: 1:43 PM
 */

namespace andrej2013\yiiboilerplate\modules\gii;

class Module extends \yii\gii\Module
{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->layout = \Yii::$app->layout;
        $this->controllerNamespace = 'andrej2013\yiiboilerplate\modules\gii\controllers';
    }

    public function checkAccess()
    {
        return parent::checkAccess(); // TODO: Change the autogenerated stub
    }
    
    protected function coreGenerators()
    {
        return [];
    }
}