<?php
/**
 * Copyright (c) 2016.
 * @author Nikola Tesic (nikolatesic@gmail.com)
 */

/**
 * Created by PhpStorm.
 * User: Nikola
 * Date: 11/17/2016
 * Time: 12:46 PM
 */
namespace andrej2013\yiiboilerplate\widget;

use yii\helpers\ArrayHelper;
use \mihaildev\ckeditor\CKEditor as BaseCKEditor;
use yii\web\View;
use Yii;

class CKEditor extends BaseCKEditor
{
    /**
     * Force our presets
     */
    public function init()
    {
        if (array_key_exists('preset', $this->editorOptions)) {
            if ($this->editorOptions['preset'] == 'basic') {
                $this->presetBasic();
            } elseif ($this->editorOptions['preset'] == 'standard') {
                $this->presetStandard();
            } elseif ($this->editorOptions['preset'] == 'full') {
                $this->presetFull();
            }
            unset($this->editorOptions['preset']);
        }
        parent::init();
    }

    /**
     *
     */
    protected function presetBasic()
    {
        $preset = require(__DIR__ . '/presets/basic.php');
        $this->editorOptions = ArrayHelper::merge($preset, $this->editorOptions);
    }

    /**
     *
     */
    private function presetStandard()
    {
        $preset = require(__DIR__ . '/presets/standard.php');
        $this->editorOptions = ArrayHelper::merge($preset, $this->editorOptions);
    }

    /**
     *
     */
    protected function presetFull()
    {
        $preset = require(__DIR__ . '/presets/full.php');
        $this->editorOptions = ArrayHelper::merge($preset, $this->editorOptions);
    }

    /**
     *
     */
    public function run()
    {
        list(, $assetPath) = Yii::$app->assetManager->publish('@vendor/mihaildev/yii2-ckeditor/editor');
        $this->view->registerJs("window['CKEDITOR_BASEPATH'] = '$assetPath/';", View::POS_BEGIN);
        parent::run(); // TODO: Change the autogenerated stub
    }
}
