<?php
/**
 * Copyright (c) 2017.
 * @author Nikola Tesic (nikolatesic@gmail.com)
 */

/**
 * Created by PhpStorm.
 * User: Nikola
 * Date: 5/19/2017
 * Time: 12:58 PM
 */

namespace andrej2013\yiiboilerplate\widget;

use Yii;
use andrej2013\yiiboilerplate\grid\GridView;
use andrej2013\yiiboilerplate\models\ActiveRecord;
use yii\base\Widget;
use yii\data\ActiveDataProvider;
use yii\widgets\LinkPager;
use yii\widgets\Pjax;

class HistoryTab extends Widget
{

    /**
     * @var ActiveRecord
     */
    public $model;

    /**
     * @var ActiveDataProvider
     */
    protected $dataProvider;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->dataProvider = new ActiveDataProvider([
            'id'         => 'history',
            'query'      => $this->model->getHistory(),
            'pagination' => [
                'pageSize'  => 20,
                'pageParam' => 'page-history',
            ],
        ]);
    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        return GridView::widget([
                'layout'       => '{summary}{items}{pager}',
                'dataProvider' => $this->dataProvider,
                'panel'        => [
                    'type'   => Yii::$app->params['style']['primary_color'],
                    'before' => false,
                    'after'  => false,
                    'footer' => false,
                ],
                'pager'        => [
                    'class'          => LinkPager::className(),
                    'firstPageLabel' => Yii::t('app', 'First'),
                    'lastPageLabel'  => Yii::t('app', 'Last'),
                ],
                'options'      => [
                    'id' => 'ar-history-grid',
                ],
                'columns'      => [
                    [
                        'class'     => '\kartik\grid\DataColumn',
                        'attribute' => 'event',
                        'content'   => function ($model) {
                            return $model->getEventName();
                        },
                    ],
                    [
                        'class'     => '\kartik\grid\DataColumn',
                        'attribute' => 'field_name',
                    ],
                    [
                        'class'     => '\kartik\grid\DataColumn',
                        'attribute' => 'created_at',
                        'format'    => 'datetime',
                    ],
                    [
                        'class'     => '\kartik\grid\DataColumn',
                        'attribute' => 'created_by',
                        'content'   => function ($model) {
                            return $model->getUserName();
                        },
                    ],
                    [
                        'class'     => '\kartik\grid\DataColumn',
                        'attribute' => 'old_value',
                    ],
                    [
                        'class'     => '\kartik\grid\DataColumn',
                        'attribute' => 'new_value',
                    ],
                ],
                'pjax'         => true,
                'striped'      => true,
                'hover'        => true,
            ]);
    }
}