<?php
/**
 * Created by PhpStorm.
 * User: Nikola
 * Date: 10/14/2016
 * Time: 8:55 AM
 */

namespace andrej2013\yiiboilerplate\widget;

use yii\base\Widget;
use yii\bootstrap\BootstrapPluginAsset;
use yii\helpers\Html;

class Modal extends \yii\bootstrap\Modal
{
    public function init()
    {
        Html::addCssClass($this->headerOptions, ['modal-header-'.\Yii::$app->params['style']['primary_color']]);
        parent::init(); // TODO: Change the autogenerated stub
    }
}
