<?php
/**
 * Copyright (c) 2017.
 * @author Nikola Tesic (nikolatesic@gmail.com)
 */

/**
 * Created by PhpStorm.
 * User: Nikola
 * Date: 7/4/2017
 * Time: 4:04 PM
 */

namespace andrej2013\yiiboilerplate\widget;

use andrej2013\yiiboilerplate\modules\userParameter\models\UserParameter;
use yii\base\InvalidConfigException;
use yii\base\Widget;
use yii\db\ActiveRecord;

class PageSize extends Widget
{
    const ALL = 'all';

    public $pjaxContainerId;

    public $model;

    public $pages;

    public function init()
    {
        if ($this->pages == null) {
            if (\Yii::$app->params['pageSize']) {
                $this->pages = \Yii::$app->params['pageSize'];
            } else {
                $this->pages = [10 => 10, 20 => 20, 50 => 50, 100 => 100, self::ALL => \Yii::t('app', 'All')];
            }
        }
        if ($this->model == null) {
            throw new InvalidConfigException('model param is required');
        }
        if (!$this->model instanceof ActiveRecord) {
            throw new InvalidConfigException('Model param need to be instance of ActiveRecord');
        }
        if ($this->pjaxContainerId == null) {
            throw new InvalidConfigException('pjaxContainerId param is required');
        }
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        return Select2::widget([
            'name' => 'pageSize',
            'data' => $this->pages,
            'value' => $this->model->getPageSize(),
            'pjaxContainerId' => $this->pjaxContainerId,
            'hideSearch' => true,
        ]);
    }
}