<?php
/**
 * Copyright (c) 2017.
 * @author Nikola Tesic (nikolatesic@gmail.com)
 */

/**
 * Created by PhpStorm.
 * User: Nikola
 * Date: 7/20/2017
 * Time: 8:47 AM
 */

namespace andrej2013\yiiboilerplate\widget;

use yii\widgets\InputWidget;
use andrej2013\yiiboilerplate\components\QrCode;
use yii\helpers\Html;

class QrInput extends InputWidget
{

    /**
     * @var string
     */
    public $format = QrCode::SVG;

    /**
     * @var int
     */
    public $size = 100;

    /**
     * @var string
     */
    public $template = '{input}{code}';

    /**
     * @var QrCode
     */
    protected $generator;

    /**
     * @throws \yii\base\InvalidConfigException
     */
    public function init()
    {
        $this->generator = new QrCode();
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     *
     */
    public function run()
    {
        $this->options['class'] = 'form-control';
        if ($this->hasModel()) {
            $replace['{input}'] = Html::activeTextInput($this->model, $this->attribute, $this->options);
        } else {
            $replace['{input}'] = Html::textInput($this->name, $this->value, $this->options);
        }
        if (!empty($this->model->{$this->attribute})) {
            $replace['{code}'] = Html::tag(
                'span',
                Html::img($this->generator->get($this->model->{$this->attribute}), ['style' => 'margin-left: 13px;']),
                ['class' => 'input-group-btn']
            );
        } else {
            $replace['{code}'] = '';
        }
        echo Html::tag(
            'div',
            strtr($this->template, $replace),
            ['class' => !empty($this->model->{$this->attribute}) ? 'input-group' : '']
        );
    }
}