<?php
/**
 * /home/ntesic/www/yii2-my-starter-kit/src/../runtime/giiant/358b0e44f1c1670b558e36588c267e47
 *
 * @package default
 */


namespace andrej2013\yiiboilerplate\modules\backend\controllers;

use andrej2013\yiiboilerplate\models\ArHistory;
use andrej2013\yiiboilerplate\models\search\ArHistorySearch;
use app\controllers\CrudController;

/**
 * ArHistoryController implements the CRUD actions for ArHistory model.
 */
class HistoryController extends CrudController
{
    public function init()
    {
        $this->model = ArHistory::class;
        $this->searchModel = \andrej2013\yiiboilerplate\models\search\ArHistory::class;
        return parent::init(); // TODO: Change the autogenerated stub
    }
}
