<?php
/**
 * /home/ntesic/www/yii2-my-starter-kit/src/../runtime/giiant/358b0e44f1c1670b558e36588c267e47
 *
 * @package default
 */


namespace andrej2013\yiiboilerplate\modules\backend\controllers;

use andrej2013\yiiboilerplate\models\UserAuthLog;
use app\controllers\CrudController;

/**
 * UserAuthLogController implements the CRUD actions for UserAuthLog model.
 */
class UserAuthLogController extends CrudController
{
    public function init()
    {
        $this->model = UserAuthLog::class;
        $this->searchModel = \andrej2013\yiiboilerplate\models\search\UserAuthLog::class;
        return parent::init(); // TODO: Change the autogenerated stub
    }
}
