# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: ilestis/bitbucket-pipelines-php-mysql
#image: smartapps/bitbucket-pipelines-php-mysql

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - service mysql start
          - mysql -h localhost -u root -proot -e "create database \`test-test\`;"
          - composer clear-cache
          - composer install --no-interaction --prefer-source --optimize-autoloader
          - cp .env-test .env
          - php yii migrate --interactive=0
          - codecept run unit