<?php
/**
 * Created by PhpStorm.
 * User: ntesic
 * Date: 2/20/19
 * Time: 10:19 PM
 */

namespace andrej2013\yiiboilerplate\templates\crud\providers;

use andrej2013\yiiboilerplate\templates\crud\Generator;
use andrej2013\yiiboilerplate\templates\crud\providers\base\Provider;

class ColorProvider extends Provider
{

    public $type = Generator::TYPE_COLOR_PICKER;

    public function activeField($attribute)
    {
        if ($this->condition($attribute)) {
            $options = [
                'options' => [
                    'pluginOptions' => [
                        'autoclose' => true,
                        'class'     => "'form-control'",
                    ],
                ],
            ];
            $options = $this->generator->var_export54($options);
            $method = __METHOD__;
            return <<<HTML
/*Generated by $method*/
\$form->field(
    \$model,
    '{$attribute}',
    [
        'selectors' => [
            'input' => '#'.Html::getInputId(\$model, '$attribute') . \$caller_id,
        ]
    ]
    )
     ->widget(\\kartik\\color\\ColorInput::class, $options
     )
    ->hint(\$model->getAttributeHint('$attribute'));
HTML;

        }
    }
}