<?php
/**
 * Copyright (c) 2017.
 * @author Nikola Tesic (nikolatesic@gmail.com)
 */

/**
 * Created by PhpStorm.
 * User: ben-g
 * Date: 18.01.2016
 * Time: 10:27
 */
/**
 * @property \andrej2013\yiiboilerplate\modules\share\models\FlysystemUser[] $flysystemUsers
 * @property \andrej2013\yiiboilerplate\modules\share\models\Flysystem[]     $flysystems
 * @property \andrej2013\yiiboilerplate\modules\user\models\Profile          $profile
 */
namespace andrej2013\yiiboilerplate\modules\user\models;

use andrej2013\yiiboilerplate\rest\Token;
use yii\db\Query;
use yii\helpers\ArrayHelper;
use yii\web\UnauthorizedHttpException;
use Yii;

class User extends \dektrium\user\models\User
{

    /**
     * @var \app\models\User
     */
    private static $_instance;
    
    private static $role;
    
    /**
     * User's toString method. Can be overridden.
     * @return mixed
     */
    public function toString()
    {
        return !empty($this->profile->name) ? $this->profile->name : $this->username;
    }

    /**
     * Getter for toString() function
     * @return String
     */
    public function getToString()
    {
        return $this->toString();
    }

    /**
     * @param mixed $token
     * @param null  $type
     * @return User
     * @throws UnauthorizedHttpException
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        /** @var Token $t */
        $tokenModel = Token::find()->where(['code' => $token])->one();

        if ($tokenModel == null) {
            throw new UnauthorizedHttpException("not a valid access token");
        }
        if ($tokenModel->isExpired) {
            $tokenModel->delete();
            throw new UnauthorizedHttpException("access token is expired");
        }

        $tokenModel->created_at = time();
        $tokenModel->save(false, ['created_at']);

        /** @var User $user */
        $user = User::findOne($tokenModel->user_id);

        return $user;
    }

    /**
     * Check if user is admin
     * @return bool
     */
    public function getIsAdmin()
    {
        return parent::getIsAdmin() || $this->checkAdminRoles();
    }

    /**
     * Check if user has admin roles
     * @return bool
     */
    private function checkAdminRoles()
    {
        foreach (Yii::$app->authManager->getRolesByUser($this->id) as $role) {
            if (in_array($role->name, Yii::$app->user->rootRoles)) {
                return true;
            }
        }
        return false;
    }

    /**
     * @param null $options
     * @return mixed|null
     * @throws \Exception
     */
    public function getProfilePicture($options = null)
    {
        if ($this->profile == null || $this->profile->picture == null) {
            return '/images/user.svg';
        }
        return $this->profile->getFileUrl('picture', $options);
    }

    /**
     * User for filtering results for Select2 element
     * @param null $q
     * @return array
     */
    public static function filter($q = null)
    {
        Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        $out = ['results' => ['id' => '', 'text' => '']];
        if (!is_null($q)) {
            $query = new Query();
            $query->select(['id', 'text' => Profile::tableName() . '.name'])
                ->leftJoin(Profile::tableName(), Profile::tableName() . '.user_id = ' . User::tableName() . '.id')
                ->from(self::tableName())
                ->andWhere([\app\models\User::tableName() . '.blocked_at' => null])
                ->andWhere(['like', Profile::tableName() . '.name', $q])
                ->limit(20);
            $command = $query->createCommand();
            $data = $command->queryAll();
            $out['results'] = array_values($data);
        }
        return $out;
    }

    /**
     * @param $insert
     * @param $changedAttributes
     */
    public function afterSave($insert, $changedAttributes)
    {
        // This will take care of the dektrium profile
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub

        // Since the previous afterSave takes care of creating the profile (from dektrium), this doesn't make much sense.
        // It should allow to override the default profile class, but this condition will never be true.
        if ($insert && !$this->profile) {
            $profile = Yii::createObject($this->module->modelMap['Profile']);
            $profile->name = $this->username;
            $profile->user_id = $this->id;
            $profile->save(false);
        }
    }

    /**
     * @return mixed
     */
    public function beforeDelete()
    {
        if ($this->profile) {
            $this->profile->delete();
        }
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

    /**
     * @return \app\models\User
     */
    public static function getInstance()
    {
        if (self::$_instance === null) {
            self::$_instance = \Yii::$app->user->identity;
        }
        return self::$_instance;
    }
    
    /**
     * Return if assigned to this role only, not as Yii::$app->user->can(), since sometimes in role hiararchy we need exactly
     * to check if user is assigned only to this role
     * @param $role
     * @return bool
     */
    public function isRole($role)
    {
        if (self::$role === null) {
            self::$role = array_keys(\Yii::$app->authManager->getRolesByUser($this->id));
        }
        return in_array($role, self::$role);
    }

}
