<?php
/**
 * /home/ntesic/www/yii2-my-starter-kit/src/../runtime/giiant/a0a12d1bd32eaeeb8b2cff56d511aa22
 *
 * @package default
 */


use yii\helpers\Html;
use yii\helpers\Url;
use andrej2013\yiiboilerplate\grid\GridView;
use andrej2013\yiiboilerplate\widget\export\ExportMenu;
use yii\web\View;
use \bookin\aws\checkbox\AwesomeCheckbox;
use yii\helpers\ArrayHelper;

/**
 *
 * @var yii\web\View                                        $this
 * @var yii\data\ActiveDataProvider                         $dataProvider
 * @var andrej2013\yiiboilerplate\models\search\UserAuthLog $searchModel
 */
$this->title = Yii::t('app', 'User Auth Logs');
$this->params['breadcrumbs'][] = $this->title;


/* ------- Multiple-Delete Batch Action ------ */
$inlineScript = 'var gridViewKey = "user-auth-log";var gridSelectedRow="' . GridView::TYPE_SUCCESS . '";';
$this->registerJs($inlineScript, View::POS_HEAD, 'my-inline-js');

$gridDropdownItems = ArrayHelper::merge([
    ($searchModel->deletable() && Yii::$app->getUser()
                                           ->can(Yii::$app->controller->module->id . '_' . Yii::$app->controller->id . '_delete-multiple') ? [
        'url'     => [
            false,
        ],
        'options' => [
            'onclick'  => 'deleteMultiple(this);',
            'data-url' => Url::toRoute('delete-multiple'),
        ],
        'label'   => '<i class="fa fa-trash" aria-hidden="true"></i>&nbsp;' . Yii::t('app', 'Delete'),
    ] : ''),
], Yii::$app->controller->gridDropdownActions);

$gridColumns = [
    [
        'class'               => \kartik\grid\DataColumn::class,
        'attribute'           => 'user_id',
        'format'              => 'html',
        'content'             => function ($model) {
            $user = \app\models\User::findOne($model->user_id);
            return Html::a($user->toString, ['/user/admi/update', 'id' => $model->user_id]);
        },
        'filterType'          => GridView::FILTER_SELECT2,
        'filterWidgetOptions' => [
            'data'          => \yii\helpers\ArrayHelper::map(\app\models\User::find()
                                                                             ->all(), 'id', 'toString'),
            'options'       => [
                'placeholder' => '',
                'multiple'    => true,
            ],
            'pluginOptions' => [
                'allowClear' => true,
            ],
        ],
    ],
    [
        'attribute' => 'date',
        'content'   => function ($model) {
            return date('Y-m-d H:i:s', $model->date);
        },
    ],
    /*Generated by andrej2013\yiiboilerplate\templates\crud\providers\CheckboxProvider::columnFormat*/
    [
        'attribute'  => 'cookie_based',
        'class'      => '\kartik\grid\BooleanColumn',
        'trueLabel'  => \Yii::t('app', 'Yes'),
        'falseLabel' => \Yii::t('app', 'No'),
        'content'    => function ($model) {
            return $model->cookie_based == 1 ? Yii::t('app', 'Yes') : Yii::t('app', 'No');
        },


    ],
    'duration',
    /*Generated by andrej2013\yiiboilerplate\templates\crud\providers\InputProvider::columnFormat*/
    [
        'class'               => \kartik\grid\DataColumn::class,
        'attribute'           => 'error',
        'format'              => 'html',
        'filterType'          => GridView::FILTER_TYPEAHEAD,
        'filterWidgetOptions' => [
            'pluginOptions' => [
                'highlight' => true,
            ],
            'options'       => [
                'placeholder'  => Yii::t('app', 'Filter as you type') . ' ...',
                'autocomplete' => 'off',
            ],
            'dataset'       => [
                [
                    'datumTokenizer' => 'Bloodhound.tokenizers.obj.whitespace("value")',
                    'display'        => 'value',
                    'remote'         => [
                        'url'      => Url::to(['user-auth-log/typehead', 'attribute' => 'error']) . '&q=%QUERY',
                        'wildcard' => '%QUERY',
                    ],
                    'templates'      => [
                        'notFound' => '<div class="text-danger" style="padding:0 8px">' . Yii::t('app', 'No results') . '</div>',
                    ],
                ],
            ],
        ],
    ],
    /*Generated by andrej2013\yiiboilerplate\templates\crud\providers\InputProvider::columnFormat*/
    [
        'class'               => \kartik\grid\DataColumn::class,
        'attribute'           => 'ip',
        'format'              => 'html',
        'filterType'          => GridView::FILTER_TYPEAHEAD,
        'filterWidgetOptions' => [
            'pluginOptions' => [
                'highlight' => true,
            ],
            'options'       => [
                'placeholder'  => Yii::t('app', 'Filter as you type') . ' ...',
                'autocomplete' => 'off',
            ],
            'dataset'       => [
                [
                    'datumTokenizer' => 'Bloodhound.tokenizers.obj.whitespace("value")',
                    'display'        => 'value',
                    'remote'         => [
                        'url'      => Url::to(['user-auth-log/typehead', 'attribute' => 'ip']) . '&q=%QUERY',
                        'wildcard' => '%QUERY',
                    ],
                    'templates'      => [
                        'notFound' => '<div class="text-danger" style="padding:0 8px">' . Yii::t('app', 'No results') . '</div>',
                    ],
                ],
            ],
        ],
    ],
    /*Generated by andrej2013\yiiboilerplate\templates\crud\providers\InputProvider::columnFormat*/
    [
        'class'               => \kartik\grid\DataColumn::class,
        'attribute'           => 'host',
        'format'              => 'html',
        'filterType'          => GridView::FILTER_TYPEAHEAD,
        'filterWidgetOptions' => [
            'pluginOptions' => [
                'highlight' => true,
            ],
            'options'       => [
                'placeholder'  => Yii::t('app', 'Filter as you type') . ' ...',
                'autocomplete' => 'off',
            ],
            'dataset'       => [
                [
                    'datumTokenizer' => 'Bloodhound.tokenizers.obj.whitespace("value")',
                    'display'        => 'value',
                    'remote'         => [
                        'url'      => Url::to(['user-auth-log/typehead', 'attribute' => 'host']) . '&q=%QUERY',
                        'wildcard' => '%QUERY',
                    ],
                    'templates'      => [
                        'notFound' => '<div class="text-danger" style="padding:0 8px">' . Yii::t('app', 'No results') . '</div>',
                    ],
                ],
            ],
        ],
    ],
    /*Generated by andrej2013\yiiboilerplate\templates\crud\providers\InputProvider::columnFormat*/
    [
        'class'               => \kartik\grid\DataColumn::class,
        'attribute'           => 'url',
        'format'              => 'html',
        'filterType'          => GridView::FILTER_TYPEAHEAD,
        'filterWidgetOptions' => [
            'pluginOptions' => [
                'highlight' => true,
            ],
            'options'       => [
                'placeholder'  => Yii::t('app', 'Filter as you type') . ' ...',
                'autocomplete' => 'off',
            ],
            'dataset'       => [
                [
                    'datumTokenizer' => 'Bloodhound.tokenizers.obj.whitespace("value")',
                    'display'        => 'value',
                    'remote'         => [
                        'url'      => Url::to(['user-auth-log/typehead', 'attribute' => 'url']) . '&q=%QUERY',
                        'wildcard' => '%QUERY',
                    ],
                    'templates'      => [
                        'notFound' => '<div class="text-danger" style="padding:0 8px">' . Yii::t('app', 'No results') . '</div>',
                    ],
                ],
            ],
        ],
    ],
    /*Generated by andrej2013\yiiboilerplate\templates\crud\providers\InputProvider::columnFormat*/
    [
        'class'               => \kartik\grid\DataColumn::class,
        'attribute'           => 'user_agent',
        'format'              => 'html',
        'filterType'          => GridView::FILTER_TYPEAHEAD,
        'filterWidgetOptions' => [
            'pluginOptions' => [
                'highlight' => true,
            ],
            'options'       => [
                'placeholder'  => Yii::t('app', 'Filter as you type') . ' ...',
                'autocomplete' => 'off',
            ],
            'dataset'       => [
                [
                    'datumTokenizer' => 'Bloodhound.tokenizers.obj.whitespace("value")',
                    'display'        => 'value',
                    'remote'         => [
                        'url'      => Url::to(['user-auth-log/typehead', 'attribute' => 'user_agent']) . '&q=%QUERY',
                        'wildcard' => '%QUERY',
                    ],
                    'templates'      => [
                        'notFound' => '<div class="text-danger" style="padding:0 8px">' . Yii::t('app', 'No results') . '</div>',
                    ],
                ],
            ],
        ],
    ],
];
$exportColumns = $gridColumns;
$gridConfig = Yii::createObject([
    'class'   => \andrej2013\yiiboilerplate\modules\backend\models\GridConfig::class,
    'columns' => $gridColumns,
    'model'   => $searchModel,
    'grid_id' => 'user-auth-log-grid',
]);
$slicedGridColumns = $gridConfig->sliceColumns();
foreach ($exportColumns as $column => $value) {
    // Remove checkbox and action columns from Excel export
    if (isset($value['hiddenFromExport']) && $value['hiddenFromExport']) {
        unset($exportColumns[$column]);
    }
}
?>

<div class="box box-<?php echo \Yii::$app->params['style']['primary_color']; ?>">
    <div class="giiant-crud box-body user-auth-log-index">
        <div class="table-responsive">
            <?php echo GridView::widget([
                'dataProvider'     => $dataProvider,
                'filterModel'      => $searchModel,
                'filterSelector'   => 'select[name="pageSize"]',
                'options'          => [
                    'id' => 'user-auth-log-grid',
                ],
                'columns'          => $slicedGridColumns,
                'responsive'       => false,
                'containerOptions' => [
                    'style' => 'overflow: auto',
                ], // only set when $responsive = false
                'headerRowOptions' => [
                    'class' => 'kartik-sheet-style',
                ],
                'filterRowOptions' => [
                    'class' => 'kartik-sheet-style',
                ],
                'toolbar'          => [
                    [
                        'content' => Html::button('<i class="fa fa-info"></i> ', [
                            'class'       => 'btn',
                            'color'       => Html::TYPE_DEFAULT,
                            'data-toggle' => 'modal',
                            'data-target' => '#info_modal',
                        ]),
                    ],
                    [
                        'content' => Html::a('<i class="fa fa-ban"></i>', ['index', 'reset' => 1], [
                            'class' => 'btn',
                            'color' => Html::TYPE_DEFAULT,
                            'title' => Yii::t('app', 'Reset Grid'),
                        ]),
                    ],
                    [
                        'content' => \andrej2013\yiiboilerplate\widget\PageSize::widget([
                            'pjaxContainerId' => 'user-auth-log-pjax-container',
                            'model'           => $searchModel,
                        ]),
                    ],
                    [
                        'content' => \yii\bootstrap\ButtonDropdown::widget([
                            'id'          => 'actions',
                            'encodeLabel' => false,
                            'label'       => Yii::t('app', 'Actions'),
                            'dropdown'    => [
                                'options'      => [
                                    'class' => 'dropdown-menu-right',
                                ],
                                'encodeLabels' => false,
                                'items'        => $gridDropdownItems,
                            ],
                            'options'     => [
                                'class' => 'btn',
                                'color' => Html::TYPE_DEFAULT,
                                'style' => (empty($gridDropdownItems) ? 'display: none' : null),
                            ],
                        ]),
                    ],
                ],
                'panel'            => [
                    'heading' => '<h4 class="panel-title"><i class="fa fa-list-o"></i> ' . Yii::t('app', 'User Auth Logs') . '</h4>',
                    'type'    => Yii::$app->params['style']['primary_color'],
                    'before'  => false,
                    'after'   => '{pager}',
                    'footer'  => false,
                ],
                // set export properties
                'export'           => [
                    'fontAwesome'      => true,
                    'label'            => Yii::t('app', 'Export'),
                    'options'          => [
                        'class' => 'btn',
                        'color' => Html::TYPE_DEFAULT,
                    ],
                    'showConfirmAlert' => false,
                ],
                'exportConfig'     => [
                    GridView::PDF   => [],
                    GridView::HTML  => [],
                    GridView::CSV   => [],
                    GridView::TEXT  => [],
                    GridView::JSON  => [],
                    GridView::EXCEL => [
                        //Override default export option with ExportMenu Widget
                        'external' => true,
                        'label'    => ExportMenu::widget([
                            'asDropdown'         => false,
                            'dataProvider'       => $dataProvider,
                            'showColumnSelector' => false,
                            'columns'            => $exportColumns,
                            'fontAwesome'        => true,
                            'exportConfig'       => [
                                ExportMenu::FORMAT_HTML  => false,
                                ExportMenu::FORMAT_PDF   => false,
                                ExportMenu::FORMAT_CSV   => false,
                                ExportMenu::FORMAT_EXCEL => false,
                                ExportMenu::FORMAT_TEXT  => false,
                            ],
                        ]),
                    ],
                ],
                'striped'          => true,
                'pjax'             => true,
                'pjaxSettings'     => [
                    'options'       => [
                        'id' => 'user-auth-log-pjax-container',
                    ],
                    'clientOptions' => [
                        'method' => 'POST',
                    ],
                ],
                'hover'            => true,
                'pager'            => [
                    'class'          => yii\widgets\LinkPager::className(),
                    'firstPageLabel' => Yii::t('app', 'First'),
                    'lastPageLabel'  => Yii::t('app', 'Last'),
                ],
            ])
            ?>
        </div>
    </div>
</div>
<?php
\andrej2013\yiiboilerplate\widget\Modal::begin([
    'header'       => Html::tag('h4', Yii::t('app', 'Information')),
    'toggleButton' => false,
    'id'           => 'info_modal',
    'footer'       => Html::a('<span class="fa fa-ban"></span>&nbsp;' . Yii::t('app', 'Close'), ['#'], [
        'class'        => 'btn btn-danger pull-left',
        'data-dismiss' => 'modal',
    ]),

]); ?><?php echo $this->render('@andrej2013-boilerplate/views/_info_modal') ?><?php \andrej2013\yiiboilerplate\widget\Modal::end();
?>
