<?php

use \dmstr\bootstrap\Tabs;
use yii\bootstrap\ActiveForm;
use yii\helpers\ArrayHelper;
use yii\helpers\Inflector;
use yii\helpers\Url;
use yii\helpers\Html;
use andrej2013\yiiboilerplate\widget\Select2;
use andrej2013\yiiboilerplate\widget\DepDrop;
use andrej2013\yiiboilerplate\modules\backend\widgets\RelatedForms;

/**
 * @var yii\web\View           $this
 * @var app\models\Faq         $model
 * @var yii\widgets\ActiveForm $form
 * @var array                  $pk
 * @var array                  $show
 * @var string                 $action
 * @var boolean                $is_popup  value to know if this form is in popup
 * @var string                 $caller_id represent id of select2 input from which is popup opened. In main form it is always ID without anything appended
 */

$caller_id = $is_popup ? ('_from_' . $caller_id) : '';
?>
<div class="hide header_title"><?php echo Html::tag('h4', Yii::t('app', 'Faq')); ?></div>
<div class="faq-form">
    <?php $form = ActiveForm::begin([
        'fieldClass'             => '\andrej2013\yiiboilerplate\widget\ActiveField',
        'id'                     => 'Faq' . ($is_popup ? '_popup_' . $caller_id : ''),
        'layout'                 => 'horizontal',
        'enableClientValidation' => true,
        'errorSummaryCssClass'   => 'error-summary alert alert-error',
        'action'                 => \yii\helpers\Url::current(),
        'options'                => [
            'name' => 'Faq',
        ],
    ]);
    ?>
    <?php $this->beginBlock('main'); ?>
    <?= /*Generated by andrej2013\yiiboilerplate\templates\crud\providers\InputProvider::activeField*/
    $form->field($model, 'title', [
        'selectors' => [
            'input' => '#' . Html::getInputId($model, 'title') . $caller_id,
        ],
    ])
         ->textInput([
             'id'          => Html::getInputId($model, 'title') . $caller_id,
             'placeholder' => $model->getAttributePlaceholder('title'),
             'maxlenght'   => 255,
         ])
         ->hint($model->getAttributeHint('title')); ?>
    <?php echo $form->field($model, 'content', [
        'selectors' => [
            'input' => '#' . Html::getInputId($model, 'content') . $caller_id,
        ],
    ])
                    ->widget(\andrej2013\yiiboilerplate\widget\CKEditor::classname(), [
                        'editorOptions' => \mihaildev\elfinder\ElFinder::ckeditorOptions('elfinder-backend', [
                            'height' => 300,
                            'preset' => 'standard',
                        ]),
                    ])
                    ->hint($model->getAttributeHint('content'))
    ?>

    <?= /*Generated by andrej2013\yiiboilerplate\templates\crud\providers\Select2Provider::activeField*/
    (isset($hide) && $hide === 'language_id')
        ? Html::activeHiddenInput($model, 'language_id', [
        'id' => 'language_id' . ($is_popup ? '_from' . $caller_id : ''),
    ])
        : $form->field($model, 'language_id')
               ->widget(Select2::class, [
                   'data'          => \andrej2013\yiiboilerplate\models\Language::find()
                                                                                ->andWhere(['status' => 1])
                                                                                ->count() > 50
                       ? null
                       : ArrayHelper::map(\andrej2013\yiiboilerplate\models\Language::find()
                                                                                    ->andWhere(['status' => 1])
                                                                                    ->all(), 'language_id', 'toString'),
                   'initValueText' => \andrej2013\yiiboilerplate\models\Language::find()
                                                                                ->count() > 50 ? ArrayHelper::map(\andrej2013\yiiboilerplate\models\Language::find()
                                                                                                                                                            ->andWhere(['status' => 1])
                                                                                                                                                            ->all(), 'language_id', 'toString') : '',
                   'options'       => [
                       'placeholder' => Yii::t('app', 'Select a value...'),
                       'id'          => 'language_id' . ($is_popup ? '_from' . $caller_id : ''),
                   ],
                   'pluginOptions' => [
                       'allowClear'         => false,
                       'minimumInputLength' => \andrej2013\yiiboilerplate\models\Language::find()
                                                                                         ->andWhere(['status' => 1])
                                                                                         ->count() > 50 ? 3 : false,
                       'ajax'               => \andrej2013\yiiboilerplate\models\Language::find()
                                                                                         ->andWhere(['status' => 1])
                                                                                         ->count() > 50 ? [
                           'url'      => \yii\helpers\Url::to(['language/select-search']),
                           'dataType' => 'json',
                           'data'     => new \yii\web\JsExpression('function(params) {
                            return {
                                q:params.term
                            };
                        }'),
                       ] : null,
                   ],
                   'is_popup'      => $is_popup,
               ]); ?>
    <?= $form->field($model, 'level')
             ->widget(DepDrop::classname(), [
                 'type'           => DepDrop::TYPE_SELECT2,
                 'data'           => $model->language_id ? ArrayHelper::merge([\andrej2013\yiiboilerplate\modules\faq\models\Faq::ROOT_LEVEL => Yii::t('app', 'Root')], ArrayHelper::map(\andrej2013\yiiboilerplate\modules\faq\models\Faq::find()
                                                                                                                                                                                                                                          ->andWhere(['language_id' => $model->language_id])
                                                                                                                                                                                                                                          ->all(), 'id', 'toString')) : [],
                 'options'        => [
                     'placeholder' => Yii::t('app', 'Select a value...'),
                     'id'          => 'level',
                 ],
                 'select2Options' => [
                     'pluginOptions' => [
                         'allowClear' => false,
                     ],
                 ],
                 'pluginOptions'  => [
                     'depends'    => ['language_id'],
                     'url'        => Url::to(['depend', 'on' => 'Language', 'onRelation' => 'language_id']),
                     'allowClear' => false,
                 ],
             ])
             ->hint($model->getAttributeHint('level')) ?>
    <?= /*Generated by andrej2013\yiiboilerplate\templates\crud\providers\InputProvider::activeField*/
    $form->field($model, 'order', [
        'selectors' => [
            'input' => '#' . Html::getInputId($model, 'order') . $caller_id,
        ],
    ])
         ->textInput([
             'id'          => Html::getInputId($model, 'order') . $caller_id,
             'placeholder' => $model->getAttributePlaceholder('order'),
             'type'        => 'number',
             'step'        => 1,
         ])
         ->hint($model->getAttributeHint('order')); ?>
    <?php
    echo $form->field($model, 'place')
              ->hiddenInput(['value' => \andrej2013\yiiboilerplate\modules\faq\models\Faq::PLACE_BACKEND])
              ->label('');
    ?>
    <?php $this->endBlock(); ?>
    <div class="nav-tabs-custom">
        <?= Tabs::widget([
            'encodeLabels' => false,
            'items'        => [
                [
                    'label'   => Yii::t('app', Inflector::camel2words('Faq')),
                    'content' => $this->blocks['main'],
                    'active'  => true,
                ],
            ],
        ]) ?>    </div>
    <?php echo $form->errorSummary($model); ?>
    <div class="pull-right">
        <?= Html::submitButton('<span class="fa fa-check"></span> ' . ($model->isNewRecord && ! $multiple ? Yii::t('app', 'Create') : Yii::t('app', 'Save')), [
            'id'     => 'save-' . $model->formName(),
            'class'  => 'btn',
            'preset' => Html::PRESET_PRIMARY,
            'name'   => 'submit-default',
        ]); ?>
        <?php if (! $is_popup) { ?>
            <?= Html::submitButton('<span class="fa fa-check"></span> ' . ($model->isNewRecord && ! $multiple ? Yii::t('app', 'Create & New') : Yii::t('app', 'Save & New')), [
                'id'     => 'save-' . $model->formName(),
                'class'  => 'btn',
                'preset' => Html::PRESET_SECONDARY,
                'name'   => 'submit-new',
            ]); ?>
            <?= Html::submitButton('<span class="fa fa-check"></span> ' . ($model->isNewRecord && ! $multiple ? Yii::t('app', 'Create & Close') : Yii::t('app', 'Save & Close')), [
                'id'     => 'save-' . $model->formName(),
                'class'  => 'btn',
                'preset' => Html::PRESET_SECONDARY,
                'name'   => 'submit-close',
            ]); ?>
        <?php } ?>
    </div>
    <?php if (! $model->isNewRecord && Yii::$app->getUser()
                                                ->can(Yii::$app->controller->module->id . '_' . Yii::$app->controller->id . '_delete') && $model->deletable() && ! $is_popup) { ?>
        <?= Html::a('<span class="fa fa-trash"></span> ' . Yii::t('app', 'Delete'), ['delete', 'id' => $model->id], [
            'class'        => 'btn btn-danger',
            'preset'       => Html::PRESET_DANGER,
            'data-confirm' => '' . Yii::t('app', 'Are you sure to delete this item?') . '',
            'data-method'  => 'post',
        ]); ?>
    <?php } ?>
    <?php if ($is_popup) { ?>
        <?= Html::a('<span class="fa fa-ban"></span> ' . Yii::t('app', 'Close'), ['#'], [
            'class'        => 'btn btn-danger pull-left',
            'preset'       => Html::PRESET_DANGER,
            'data-dismiss' => 'modal',
            'name'         => 'close',
        ]); ?>
    <?php } ?>
    <?php ActiveForm::end(); ?>
    <div class="clearfix"></div>
</div>
