<?php

use dmstr\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
use dmstr\bootstrap\Tabs;

/**
 * @var yii\web\View $this
 * @var app\modules\faq\models\Faq $model
 */
$copyParams = $model->attributes;

$this->title = 'Faq ' . $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Faqs', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string)$model->title, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'View');
?>
<div class="box box-default">
    <div class="giiant-crud box-body" id="faq-view">

        <!-- flash message -->
        <?php if (\Yii::$app->session->getFlash('deleteError') !== null) : ?>
            <span class="alert alert-info alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <?= \Yii::$app->session->getFlash('deleteError') ?>
            </span>
        <?php endif; ?>

        <h1>
            <?= Yii::t('app', 'Faq') ?>
            <small>
                <?= $model->title ?>
            </small>
        </h1>


        <div class="clearfix crud-navigation">
            <!-- menu buttons -->
            <div class='pull-left'>
                <?= Html::a('<span class="glyphicon glyphicon-pencil"></span> ' . Yii::t('app', 'Edit'), ['update', 'id' => $model->id], ['class' => 'btn btn-info']) ?>
                <?= Html::a('<span class="glyphicon glyphicon-copy"></span> ' . Yii::t('app', 'Copy'), ['create', 'id' => $model->id, 'Faq' => $copyParams], ['class' => 'btn btn-success']) ?>
                <?= Html::a('<span class="glyphicon glyphicon-plus"></span> ' . Yii::t('app', 'New'), ['create'], ['class' => 'btn btn-success']) ?>
            </div>
            <div class="pull-right">
                <?= Html::a('<span class="glyphicon glyphicon-list"></span> ' . Yii::t('app', 'List Faqs'), ['index'], ['class' => 'btn btn-default']) ?>
            </div>

        </div>


        <?php $this->beginBlock('app\modules\faq\models\Faq'); ?>


        <?= DetailView::widget([
            'model' => $model,
            'attributes' => [
                'id',
                'title',
                [
                    'attribute' => 'content',
                    'format' => 'raw',
                ],
                // generated by andrej2013\yiiboilerplate\templates\crud\providers\RelationProvider::attributeFormat
                [
                    'format' => 'html',
                    'attribute' => 'language_id',
                    'value' => ($model->getLanguage()->one() ? Html::a($model->getLanguage()->one()->name, ['language/view', 'language_id' => $model->getLanguage()->one()->language_id,]) : '<span class="label label-warning">?</span>'),
                ],
                [
                    'attribute' => 'place',
                    'content' => function ($model) {
                        return \Yii::t('app', $model->place);
                    },
                ],
                [
                    'attribute' => 'level',
                    'value' => $model->levelName,
                ],
                'order',
            ],
        ]); ?>


        <hr/>

        <?= Html::a('<span class="glyphicon glyphicon-trash"></span> ' . Yii::t('app', 'Delete'), ['delete', 'id' => $model->id],
            [
                'class' => 'btn btn-danger',
                'data-confirm' => '' . Yii::t('app', 'Are you sure to delete this item?') . '',
                'data-method' => 'post',
            ]); ?>

        <?php $this->endBlock(); ?>



        <?= Tabs::widget(
            [
                'id' => 'relation-tabs',
                'encodeLabels' => false,
                'items' => [
                    [
                        'label' => '<b class=""># ' . $model->id . '</b>',
                        'content' => $this->blocks['app\modules\faq\models\Faq'],
                        'active' => true,
                    ],
                ]
            ]
        );
        ?>
        <?= andrej2013\yiiboilerplate\RecordHistory::widget(['model' => $model]) ?>
    </div>
</div>
