<?php
/**
 * Created by PhpStorm.
 * User: ntesic
 * Date: 2/2/19
 * Time: 6:01 PM
 */

namespace andrej2013\yiiboilerplate\modules\backend\widgets;

use kartik\switchinput\SwitchInput;
use yii\bootstrap\Widget;
use yii\helpers\Html;
use andrej2013\yiiboilerplate\widget\Modal;
use Yii;
use yii\helpers\Url;

class GridConfig extends Widget
{
    /**
     * @var string
     */
    public $model;

    /**
     * @var string
     */
    public $grid;

    /**
     * @var array
     */
    public $columns;

    /**
     * @var string
     */
    public $pjaxContainerId;

    public function init()
    {
        return parent::init();
    }

    public function run()
    {
        Modal::begin([
            'header'       => Html::tag('h4', Yii::t('app', 'Table Configuration')),
            'id'           => 'grid_config',
            'footer'       => Html::submitButton('<span class="fa fa-check"></span>&nbsp;' . Yii::t('app', 'Save'), [
                    'class'  => 'btn pull-right',
                    'preset' => Html::PRESET_PRIMARY,
                    'form'   => 'grid_config_form',
                ]) . Html::a('<span class="fa fa-ban"></span>&nbsp;' . Yii::t('app', 'Cancel'), ['#'], [
                    'class'        => 'btn',
                    'preset'       => Html::PRESET_DANGER,
                    'data-dismiss' => 'modal',
                ]),
            'toggleButton' => [
                'tag'   => 'button',
                'label' => '<i class="fa fa-cogs"></i>',
                'class' => 'btn',
                'color' => Html::TYPE_DEFAULT,
            ],
        ]);
        echo Html::beginForm(Url::toRoute(['backend/grid-config/index']), 'post', [
            'class'     => 'form-default',
            'id'        => 'grid_config_form',
            'data-pjax' => 1,

        ]);
        $this->renderFields();
        echo Html::tag('div', null, ['class' => 'clearfix']);
        echo Html::endForm();
        Modal::end();

        parent::run(); // TODO: Change the autogenerated stub
    }

    protected function renderFields()
    {
        $gridConfig = new \andrej2013\yiiboilerplate\modules\backend\models\GridConfig();
        $gridConfig = Yii::createObject([
            'class'   => \andrej2013\yiiboilerplate\modules\backend\models\GridConfig::class,
            'columns' => $this->columns,
            'model'   => $this->model,
            'grid_id' => $this->grid,
        ]);
        $columns = $gridConfig->parseColumns();
        echo Html::hiddenInput('grid', $this->grid);
        foreach ($columns as $column) {
            $gridConfig = \andrej2013\yiiboilerplate\modules\backend\models\GridConfig::findOne([
                'user_id' => Yii::$app->user->id,
                'grid'    => $this->grid,
                'column'  => $column['attribute'],
            ]);
            $value = $gridConfig && $gridConfig->show === 0 ? 0 : 1;
            echo Html::beginTag('div', ['class' => 'col-sm-6']);
            echo Html::beginTag('div', ['class' => 'form-group']);
            echo Html::label($column['label'], "grid_config_" . $column['attribute'], ['class' => 'control-label']);
            echo SwitchInput::widget([
                'name'          => 'GridConfig['.$column['attribute'].']',
                'id'            => 'grid_config_' . $column['attribute'],
                'value'         => $value,
                'pluginOptions' => [
                    'handleWidth' => 60,
                    'onText'      => Yii::t('app', 'Show'),
                    'offText'     => Yii::t('app', 'Hide'),
                ],
            ]);
            echo Html::endTag('div');
            echo Html::endTag('div');
        }
    }
}