<?php
/**
 * Copyright (c) 2017.
 * @author Nikola Tesic (nikolatesic@gmail.com)
 */

/**
 * Created by PhpStorm.
 * User: Nikola
 * Date: 7/24/2017
 * Time: 9:45 AM
 */

namespace andrej2013\yiiboilerplate\components;

use yii\helpers\FileHelper;

class GoogleApiLibrary extends \quexer\googleapi\GoogleApiLibrary
{

    /**
     * @var
     */
    public $fileName;

    /**
     * @param null $address
     * @param null $latlng
     * @param bool $setMarker
     * @return string
     */
    public function createImage($address = null, $latlng = null, $setMarker = false)
    {
        $createdImage =  \Yii::getAlias($this->webroot . DIRECTORY_SEPARATOR . $this->map_image_path . DIRECTORY_SEPARATOR . parent::createImage($address, $latlng, $setMarker)); // TODO: Change the autogenerated stub
        $newImage = \Yii::getAlias($this->webroot . DIRECTORY_SEPARATOR . $this->map_image_path . DIRECTORY_SEPARATOR . $this->fileName . '.png');
        if ($this->fileName != null) {
            rename($createdImage, $newImage);
            return $this->fileName . '.png';
        }
        return $createdImage;
    }
}