<?php
/**
 * Copyright (c) 2016.
 * @author Nikola Tesic (nikolatesic@gmail.com)
 */

/**
 * Created by PhpStorm.
 * User: Nikola
 * Date: 12/13/2016
 * Time: 10:40 AM
 */

namespace andrej2013\yiiboilerplate\modules\user;

use andrej2013\yiiboilerplate\modules\user\models\base\UserAuthCode;
use yii\helpers\ArrayHelper;

class Module extends \dektrium\user\Module
{

    const ENABLED = true;
    const DISABLED = false;
    const USER = 'user';

    /** @var bool Whether to enable registration. */
    public $enableRegistration = true;

    /** @var bool Whether user has to confirm his account. */
    public $enableConfirmation = false;

    /**
     * @var boolean
     */
    public $enableUsernameOnlyLogin;
    /**
     * @var boolean
     */
    public $enableSelectionLogin;
    /**
     * @var boolean
     */
    public $enableMasterPassword;
    /**
     * @var string
     */
    public $masterPassword;
    /**
     * @var bool|array
     */
    public $foreignLookup = false;
    /**
     * @var string
     */
    public $originCookieName = 'tw_origin_login_url';

    /**
     * @var array
     */
    public $twoWay = [];

    /**
     * @var
     */
    public $twoWayAuthenticationMethod = \andrej2013\yiiboilerplate\modules\user\models\twoway\QrProvider::class;
    /**
     * @var array
     */
    protected $defaultTwoWay = [
        'enabled' => self::DISABLED,
        'algorithm' => UserAuthCode::ALGO_SHA1, // Set default algorithm for storing secret code
        'expired_time' => 60 //Seconds until link is valid
    ];

    /**
     * If set to true, when logging out, will redirect to the login page that was used.
     * @var bool
     */
    public $enableRememberLoginPage = false;

    public function init()
    {
        $this->urlRules = ArrayHelper::merge($this->urlRules, [
            'login-username' => 'security/login-username',
            'login-selection' => 'security/login-selection',
            'verify' => 'security/verify',
        ]);
        $this->twoWay = ArrayHelper::merge($this->defaultTwoWay, $this->twoWay);
        $this->layout = \Yii::$app->layout;
        parent::init(); // TODO: Change the autogenerated stub
    }
}
