<?php

namespace andrej2013\yiiboilerplate\modules\deploy\controllers;

use \dersonsena\deploy\controllers\DefaultController as Controller;
use app\modules\deploy\forms\DeployForm;

class DefaultController extends Controller
{

    public function beforeAction($action)
    {
        $this->enableCsrfValidation = false;
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        $form = new DeployForm;
        $form->deploy();

        echo "<pre>{$form->getExecText()}</pre>";
        exit();
    }
}